version: '3.8'

services:
  # Cinema API приложение
  cinema-api:
    build: .
    container_name: cinema-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cinema_api
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=False
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - cinema-network

  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: cinema-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinema_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cinema-network

  # Redis для кеширования
  redis:
    image: redis:7-alpine
    container_name: cinema-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cinema-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: cinema-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - cinema-api
    networks:
      - cinema-network

  # Мониторинг
  prometheus:
    image: prom/prometheus:latest
    container_name: cinema-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - cinema-network

  # Grafana для визуализации метрик
  grafana:
    image: grafana/grafana:latest
    container_name: cinema-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cinema-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  cinema-network:
    driver: bridge 