global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus самомониторинг
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Cinema API мониторинг
  - job_name: 'cinema-api'
    static_configs:
      - targets: ['cinema-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx мониторинг
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter (если установлен на хосте)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # Docker контейнеры
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s 